/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Entidades.Usuario;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.Slide;

/**
 *
 * @author Agustin Colongne
 */
public class Menu extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    private String usuarioLogeado;
    Slide slide;
    Color c = new Color(246, 135, 18);
    Color n = new Color(100, 100, 100);
    private String u;

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        slide = new Slide();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMiCuenta = new javax.swing.JPanel();
        jPmisVentas = new javax.swing.JPanel();
        jlMisVentas = new javax.swing.JLabel();
        jPcambiarSesion = new javax.swing.JPanel();
        jLcambiarSesion = new javax.swing.JLabel();
        panelBotonEditarPerfil = new javax.swing.JPanel();
        jlEditarPerfil = new javax.swing.JLabel();
        panelBarraTareas = new javax.swing.JPanel();
        panelNombreUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        PanelBotonHoteles = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelBotonViajes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelBotonMiCuenta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelBotonPaquetes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PanelViajes = new javax.swing.JPanel();
        panelHoteles = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        panelPaquetes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanelVerMisVentas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPaneleditarPerfil = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtMail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtNombreUsuario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtContrasenia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelRegistrarseRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMiCuenta.setBackground(new Color(0,0,0,0));
        PanelMiCuenta.setMaximumSize(new java.awt.Dimension(1500, 750));
        PanelMiCuenta.setMinimumSize(new java.awt.Dimension(1500, 750));
        PanelMiCuenta.setPreferredSize(new java.awt.Dimension(1500, 750));

        jPmisVentas.setBackground(new java.awt.Color(60, 147, 214));
        jPmisVentas.setMaximumSize(new java.awt.Dimension(125, 40));
        jPmisVentas.setMinimumSize(new java.awt.Dimension(125, 40));
        jPmisVentas.setPreferredSize(new java.awt.Dimension(125, 40));

        jlMisVentas.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 18)); // NOI18N
        jlMisVentas.setForeground(new java.awt.Color(255, 255, 255));
        jlMisVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMisVentas.setText("Mis ventas");
        jlMisVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMisVentasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPmisVentasLayout = new javax.swing.GroupLayout(jPmisVentas);
        jPmisVentas.setLayout(jPmisVentasLayout);
        jPmisVentasLayout.setHorizontalGroup(
            jPmisVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMisVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPmisVentasLayout.setVerticalGroup(
            jPmisVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMisVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPcambiarSesion.setBackground(new java.awt.Color(60, 147, 214));
        jPcambiarSesion.setMaximumSize(new java.awt.Dimension(125, 40));
        jPcambiarSesion.setMinimumSize(new java.awt.Dimension(125, 40));
        jPcambiarSesion.setPreferredSize(new java.awt.Dimension(125, 40));

        jLcambiarSesion.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 18)); // NOI18N
        jLcambiarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLcambiarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLcambiarSesion.setText("Cambiar Sesión");
        jLcambiarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcambiarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPcambiarSesionLayout = new javax.swing.GroupLayout(jPcambiarSesion);
        jPcambiarSesion.setLayout(jPcambiarSesionLayout);
        jPcambiarSesionLayout.setHorizontalGroup(
            jPcambiarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcambiarSesionLayout.createSequentialGroup()
                .addComponent(jLcambiarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPcambiarSesionLayout.setVerticalGroup(
            jPcambiarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLcambiarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelBotonEditarPerfil.setBackground(new java.awt.Color(60, 147, 214));

        jlEditarPerfil.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 18)); // NOI18N
        jlEditarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jlEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEditarPerfil.setText("Editar Perfil");
        jlEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEditarPerfilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBotonEditarPerfilLayout = new javax.swing.GroupLayout(panelBotonEditarPerfil);
        panelBotonEditarPerfil.setLayout(panelBotonEditarPerfilLayout);
        panelBotonEditarPerfilLayout.setHorizontalGroup(
            panelBotonEditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEditarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBotonEditarPerfilLayout.setVerticalGroup(
            panelBotonEditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEditarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelMiCuentaLayout = new javax.swing.GroupLayout(PanelMiCuenta);
        PanelMiCuenta.setLayout(PanelMiCuentaLayout);
        PanelMiCuentaLayout.setHorizontalGroup(
            PanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiCuentaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(PanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPmisVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPcambiarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotonEditarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1275, Short.MAX_VALUE))
        );
        PanelMiCuentaLayout.setVerticalGroup(
            PanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiCuentaLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(panelBotonEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jPmisVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jPcambiarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        getContentPane().add(PanelMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 1430, 750));

        panelBarraTareas.setBackground(new java.awt.Color(100, 100, 100));

        panelNombreUsuario.setBackground(new java.awt.Color(100, 100, 100));
        panelNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelNombreUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelNombreUsuarioMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu_32.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario_32.png"))); // NOI18N

        jlUsuario.setBackground(new Color(255,255,255,0));
        jlUsuario.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlUsuario.setText("nombre del usuario");

        javax.swing.GroupLayout panelNombreUsuarioLayout = new javax.swing.GroupLayout(panelNombreUsuario);
        panelNombreUsuario.setLayout(panelNombreUsuarioLayout);
        panelNombreUsuarioLayout.setHorizontalGroup(
            panelNombreUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNombreUsuarioLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelNombreUsuarioLayout.setVerticalGroup(
            panelNombreUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelNombreUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBotonHoteles.setBackground(new java.awt.Color(100, 100, 100));
        PanelBotonHoteles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBotonHotelesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBotonHotelesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBotonHotelesMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hotel_32.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hoteles");

        javax.swing.GroupLayout PanelBotonHotelesLayout = new javax.swing.GroupLayout(PanelBotonHoteles);
        PanelBotonHoteles.setLayout(PanelBotonHotelesLayout);
        PanelBotonHotelesLayout.setHorizontalGroup(
            PanelBotonHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBotonHotelesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelBotonHotelesLayout.setVerticalGroup(
            PanelBotonHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBotonHotelesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelBotonViajes.setBackground(new java.awt.Color(100, 100, 100));
        panelBotonViajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBotonViajesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBotonViajesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBotonViajesMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/avion_32.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Viajes");

        javax.swing.GroupLayout panelBotonViajesLayout = new javax.swing.GroupLayout(panelBotonViajes);
        panelBotonViajes.setLayout(panelBotonViajesLayout);
        panelBotonViajesLayout.setHorizontalGroup(
            panelBotonViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonViajesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonViajesLayout.setVerticalGroup(
            panelBotonViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBotonViajesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelBotonMiCuenta.setBackground(new java.awt.Color(100, 100, 100));
        panelBotonMiCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBotonMiCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBotonMiCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBotonMiCuentaMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mi cuenta");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita_32.png"))); // NOI18N

        javax.swing.GroupLayout panelBotonMiCuentaLayout = new javax.swing.GroupLayout(panelBotonMiCuenta);
        panelBotonMiCuenta.setLayout(panelBotonMiCuentaLayout);
        panelBotonMiCuentaLayout.setHorizontalGroup(
            panelBotonMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonMiCuentaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonMiCuentaLayout.setVerticalGroup(
            panelBotonMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonMiCuentaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBotonPaquetes.setBackground(new java.awt.Color(100, 100, 100));
        panelBotonPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBotonPaquetesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBotonPaquetesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBotonPaquetesMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Paquetes");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/maleta_32.png"))); // NOI18N

        javax.swing.GroupLayout panelBotonPaquetesLayout = new javax.swing.GroupLayout(panelBotonPaquetes);
        panelBotonPaquetes.setLayout(panelBotonPaquetesLayout);
        panelBotonPaquetesLayout.setHorizontalGroup(
            panelBotonPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonPaquetesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonPaquetesLayout.setVerticalGroup(
            panelBotonPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonPaquetesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBarraTareasLayout = new javax.swing.GroupLayout(panelBarraTareas);
        panelBarraTareas.setLayout(panelBarraTareasLayout);
        panelBarraTareasLayout.setHorizontalGroup(
            panelBarraTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotonMiCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotonPaquetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBotonHoteles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotonViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBarraTareasLayout.setVerticalGroup(
            panelBarraTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraTareasLayout.createSequentialGroup()
                .addComponent(panelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelBotonMiCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelBotonPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelBotonHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBotonViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 433, Short.MAX_VALUE))
        );

        getContentPane().add(panelBarraTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 0, 370, 828));

        PanelViajes.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout PanelViajesLayout = new javax.swing.GroupLayout(PanelViajes);
        PanelViajes.setLayout(PanelViajesLayout);
        PanelViajesLayout.setHorizontalGroup(
            PanelViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1430, Short.MAX_VALUE)
        );
        PanelViajesLayout.setVerticalGroup(
            PanelViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        getContentPane().add(PanelViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 1430, 750));

        panelHoteles.setBackground(new java.awt.Color(0, 255, 0));

        jButton3.setText("jButton3");

        javax.swing.GroupLayout panelHotelesLayout = new javax.swing.GroupLayout(panelHoteles);
        panelHoteles.setLayout(panelHotelesLayout);
        panelHotelesLayout.setHorizontalGroup(
            panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHotelesLayout.createSequentialGroup()
                .addContainerGap(762, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(591, 591, 591))
        );
        panelHotelesLayout.setVerticalGroup(
            panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotelesLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jButton3)
                .addContainerGap(479, Short.MAX_VALUE))
        );

        getContentPane().add(panelHoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 1430, 750));

        panelPaquetes.setBackground(new java.awt.Color(255, 0, 204));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Paquetes"));

        jRadioButton1.setText("Armar paquete");

        jRadioButton2.setText("Paquetes recomendados");

        jCheckBox1.setText("Ushuaia 5 noches ¡con Navegación Beagle! 19 oct. 2023 a 24 oct. 2023 Ushuaia");

        jCheckBox2.setText("Ushuaia de Lujo 3 noches ¡Con Navegación Canal Beagle! 19 oct. 2023 a 22 oct. 2023 Ushuaia");

        jCheckBox3.setText("Calafate y Ushuaia de Lujo 19 oct. 2023 a 25 oct. 2023 El Calafate y Ushuaia");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addGap(131, 131, 131))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabel13.setText("Desde ciudad");

        jLabel14.setText("Ciudad destino");

        jLabel15.setText("Fecha de viaje");

        jLabel20.setText("Alojamiento");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Persona", "2 Personas", "3 Personas", "4 Personas", "5 Personas", "6 Personas", " " }));

        jButton1.setText("Buscar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addGap(114, 114, 114)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(jTextField1))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(129, 129, 129))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPaquetesLayout = new javax.swing.GroupLayout(panelPaquetes);
        panelPaquetes.setLayout(panelPaquetesLayout);
        panelPaquetesLayout.setHorizontalGroup(
            panelPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaquetesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaquetesLayout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        panelPaquetesLayout.setVerticalGroup(
            panelPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaquetesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelPaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 1430, 750));

        jPanelVerMisVentas.setBackground(new java.awt.Color(255, 255, 102));
        jPanelVerMisVentas.setMaximumSize(new java.awt.Dimension(1030, 460));
        jPanelVerMisVentas.setMinimumSize(new java.awt.Dimension(1030, 460));
        jPanelVerMisVentas.setPreferredSize(new java.awt.Dimension(1030, 460));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelVerMisVentasLayout = new javax.swing.GroupLayout(jPanelVerMisVentas);
        jPanelVerMisVentas.setLayout(jPanelVerMisVentasLayout);
        jPanelVerMisVentasLayout.setHorizontalGroup(
            jPanelVerMisVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerMisVentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        jPanelVerMisVentasLayout.setVerticalGroup(
            jPanelVerMisVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerMisVentasLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelVerMisVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, -470, 770, 460));

        jPaneleditarPerfil.setBackground(new java.awt.Color(51, 51, 255));

        jLabel11.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre:");

        jLabel12.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Apellido:");

        jLabel16.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Mail:");

        jLabel17.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Nombre de Usuario:");

        jtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreUsuarioActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Contraseña:");

        jPanel2.setBackground(new java.awt.Color(60, 147, 214));
        jPanel2.setMaximumSize(new java.awt.Dimension(125, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(125, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(125, 40));

        jLabel19.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Guardar");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(60, 147, 214));
        jPanel3.setMaximumSize(new java.awt.Dimension(125, 40));
        jPanel3.setMinimumSize(new java.awt.Dimension(125, 40));

        labelRegistrarseRegistro.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        labelRegistrarseRegistro.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistrarseRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistrarseRegistro.setText("Cancelar");
        labelRegistrarseRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrarseRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistrarseRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistrarseRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPaneleditarPerfilLayout = new javax.swing.GroupLayout(jPaneleditarPerfil);
        jPaneleditarPerfil.setLayout(jPaneleditarPerfilLayout);
        jPaneleditarPerfilLayout.setHorizontalGroup(
            jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneleditarPerfilLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneleditarPerfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addGroup(jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneleditarPerfilLayout.setVerticalGroup(
            jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneleditarPerfilLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(28, 28, 28)
                .addGroup(jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneleditarPerfilLayout.createSequentialGroup()
                        .addGroup(jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(36, 36, 36)
                        .addGroup(jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(35, 35, 35)
                        .addComponent(jtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneleditarPerfilLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPaneleditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPaneleditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, -470, 770, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if (panelBarraTareas.getX() == -300) {
            slide.jPanelXDerecha(panelBarraTareas.getX(), 0, 10, 10, panelBarraTareas);
            achicarPanel(PanelMiCuenta);
            achicarPanel(PanelViajes);

            achicarPanel(panelHoteles);
            achicarPanel(panelPaquetes);

        } else {
            slide.jPanelXIzquierda(panelBarraTareas.getX(), -300, 10, 10, panelBarraTareas);
            agrandarPanel(PanelViajes);
            agrandarPanel(PanelMiCuenta);
            agrandarPanel(panelHoteles);
            agrandarPanel(panelPaquetes);
        }


    }//GEN-LAST:event_jLabel1MouseClicked

    private void panelNombreUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNombreUsuarioMouseEntered
        // TODO add your handling code here:
        entrada(panelNombreUsuario);
    }//GEN-LAST:event_panelNombreUsuarioMouseEntered

    private void panelNombreUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNombreUsuarioMouseExited
        // TODO add your handling code here:

        salida(panelNombreUsuario);
    }//GEN-LAST:event_panelNombreUsuarioMouseExited

    private void panelBotonMiCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonMiCuentaMouseEntered
        // TODO add your handling code here:
        validacionColorEntered(panelBotonMiCuenta);
    }//GEN-LAST:event_panelBotonMiCuentaMouseEntered

    private void panelBotonMiCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonMiCuentaMouseExited
        // TODO add your handling code here:
        validacionColorExited(panelBotonMiCuenta);


    }//GEN-LAST:event_panelBotonMiCuentaMouseExited

    private void panelBotonViajesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonViajesMouseEntered
        // TODO add your handling code here:
        validacionColorEntered(panelBotonViajes);
    }//GEN-LAST:event_panelBotonViajesMouseEntered

    private void panelBotonViajesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonViajesMouseExited
        // TODO add your handling code here:
        validacionColorExited(panelBotonViajes);
    }//GEN-LAST:event_panelBotonViajesMouseExited

    private void PanelBotonHotelesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonHotelesMouseEntered
        // TODO add your handling code here:
        validacionColorEntered(PanelBotonHoteles);
    }//GEN-LAST:event_PanelBotonHotelesMouseEntered

    private void PanelBotonHotelesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonHotelesMouseExited
        // TODO add your handling code here:
        validacionColorExited(PanelBotonHoteles);
    }//GEN-LAST:event_PanelBotonHotelesMouseExited

    private void panelBotonPaquetesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonPaquetesMouseEntered
        // TODO add your handling code here:
        validacionColorEntered(panelBotonPaquetes);
    }//GEN-LAST:event_panelBotonPaquetesMouseEntered

    private void panelBotonPaquetesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonPaquetesMouseExited
        // TODO add your handling code here:
        validacionColorExited(panelBotonPaquetes);
    }//GEN-LAST:event_panelBotonPaquetesMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        entrada(panelNombreUsuario);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        salida(panelNombreUsuario);
    }//GEN-LAST:event_jLabel1MouseExited

    private void panelBotonMiCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonMiCuentaMouseClicked
        // TODO add your handling code here:
        panelBotonMiCuenta.setBackground(new Color(246, 135, 18));
        sacarPaneles();
        traerPanel(PanelMiCuenta);

    }//GEN-LAST:event_panelBotonMiCuentaMouseClicked

    private void panelBotonViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonViajesMouseClicked
        // TODO add your handling code here:
        panelBotonViajes.setBackground(new Color(246, 135, 18));
        sacarPaneles();
        traerPanel(PanelViajes);

    }//GEN-LAST:event_panelBotonViajesMouseClicked

    private void PanelBotonHotelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonHotelesMouseClicked
        // TODO add your handling code here:
        PanelBotonHoteles.setBackground(new Color(246, 135, 18));
        sacarPaneles();
        traerPanel(panelHoteles);

    }//GEN-LAST:event_PanelBotonHotelesMouseClicked

    private void panelBotonPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonPaquetesMouseClicked
        // TODO add your handling code here:
        panelBotonPaquetes.setBackground(c);
        sacarPaneles();
        traerPanel(panelPaquetes);
    }//GEN-LAST:event_panelBotonPaquetesMouseClicked

    private void jtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreUsuarioActionPerformed

    private void labelRegistrarseRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarseRegistroMouseClicked
        // TODO add your handling code here:
        String nombre = jtNombre.getText();
        String apellido = jtApellido.getText();
        String nombreUsuario = jtNombreUsuario.getText();
        String contraseña = jtContrasenia.getText();

        boolean estado = true;

    }//GEN-LAST:event_labelRegistrarseRegistroMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLcambiarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcambiarSesionMouseClicked
        Entrada ev = new Entrada();

        ev.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jLcambiarSesionMouseClicked

    private void jlEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEditarPerfilMouseClicked
        // TODO add your handling code here:
        bajarPanel(jPaneleditarPerfil);
    }//GEN-LAST:event_jlEditarPerfilMouseClicked

    private void jlMisVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMisVentasMouseClicked
        // TODO add your handling code here:
        bajarPanel(jPanelVerMisVentas);
    }//GEN-LAST:event_jlMisVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotonHoteles;
    private javax.swing.JPanel PanelMiCuenta;
    private javax.swing.JPanel PanelViajes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLcambiarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelVerMisVentas;
    private javax.swing.JPanel jPaneleditarPerfil;
    private javax.swing.JPanel jPcambiarSesion;
    private javax.swing.JPanel jPmisVentas;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlEditarPerfil;
    private javax.swing.JLabel jlMisVentas;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtContrasenia;
    private javax.swing.JTextField jtMail;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtNombreUsuario;
    private javax.swing.JLabel labelRegistrarseRegistro;
    private javax.swing.JPanel panelBarraTareas;
    private javax.swing.JPanel panelBotonEditarPerfil;
    private javax.swing.JPanel panelBotonMiCuenta;
    private javax.swing.JPanel panelBotonPaquetes;
    private javax.swing.JPanel panelBotonViajes;
    private javax.swing.JPanel panelHoteles;
    private javax.swing.JPanel panelNombreUsuario;
    private javax.swing.JPanel panelPaquetes;
    // End of variables declaration//GEN-END:variables
  class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/imagenes/fondoPlaya6.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);

        }

    }

    public void entrada(JPanel panel) {
        panel.setBackground(new Color(60, 147, 214));

    }

    public void salida(JPanel panel) {
        panel.setBackground(new Color(100, 100, 100));

    }

    public void sacarPaneles() {

        if (PanelMiCuenta.getX() == 370 || PanelMiCuenta.getX() == 70) {
            panelBotonMiCuenta.setBackground(n);
            slide.jPanelXDerecha(PanelMiCuenta.getX(), 1500, 10, 10, PanelMiCuenta);
        }
        if (PanelViajes.getX() == 370 || PanelViajes.getX() == 70) {
            panelBotonViajes.setBackground(n);
            slide.jPanelXDerecha(PanelViajes.getX(), 1500, 10, 10, PanelViajes);
        }
        if (panelHoteles.getX() == 370 || panelHoteles.getX() == 70) {
            PanelBotonHoteles.setBackground(n);
            slide.jPanelXDerecha(panelHoteles.getX(), 1500, 10, 10, panelHoteles);
        }
        if (panelPaquetes.getX() == 370 || panelPaquetes.getX() == 70) {
            panelBotonPaquetes.setBackground(n);
            slide.jPanelXDerecha(panelPaquetes.getX(), 1500, 10, 10, panelPaquetes);
        }
    }
    
    public void validacionColorEntered(JPanel panel) {
        if (c.getRGB() != panel.getBackground().getRGB() && n.getRGB() == panel.getBackground().getRGB()) {
            entrada(panel);
        }
    }

    public void validacionColorExited(JPanel panel) {
        if (c.getRGB() != panel.getBackground().getRGB()) {
            salida(panel);
        }

    }

    public void agrandarPanel(JPanel panel) {
        if (panel.getX() == 370) {
            slide.jPanelXIzquierda(panel.getX(), 70, 10, 10, panel);
        }

    }

    public void achicarPanel(JPanel panel) {
        if (panel.getX() == 70) {
            slide.jPanelXDerecha(panel.getX(), 370, 10, 10, panel);
        }

    }

    public void traerPanel(JPanel panel) {

        if (panelBarraTareas.getX() == 0) {
            slide.jPanelXIzquierda(panel.getX(), 370, 10, 10, panel);
        } else {
            slide.jPanelXIzquierda(panel.getX(), 70, 10, 10, panel);
        }

    }
    
    public void bajarPanel(JPanel panel){
        slide.jPanelYAbajo(panel.getY(), 100, 10, 10, panel);
        if(panelBarraTareas.getX() == 0){
            slide.jPanelXDerecha(panel.getX(), 520, 10, 100, panel);
        
        }
    
    }

    public void recuperarUsuario(String usuarioRecuperado) {
        u = usuarioRecuperado;
        jlUsuario.setText(u);

    }
}
